# -*- coding: utf-8 -*-
"""project1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w2smJvtERM1YsRqXL3WHPDzilomDjKxw
"""

from google.colab import drive
drive.mount('/content/drive')

# Passo 1: Importar base de  dados
import pandas as pd

tabela_vendas = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Vendas.xlsx")
display(tabela_vendas)

# Passo 2: Calcular o faturamento da loja
tabela_faturamento = tabela_vendas[["ID Loja", "Valor Final"]].groupby("ID Loja").sum()
tabela_faturamento = tabela_faturamento.sort_values(by="Valor Final", ascending=False)
display(tabela_faturamento)

# Passo 3: Quantidade de produtos vendidos em cada loja
tabela_quantidade = tabela_vendas[["ID Loja", "Quantidade"]].groupby("ID Loja").sum()
display(tabela_quantidade)

# Passo 4: Calcular o ticket médio
ticket_medio = (tabela_faturamento["Valor Final"] / tabela_quantidade["Quantidade"]).to_frame()
ticket_medio = ticket_medio.rename(columns={0: "Ticket Médio"})
display(ticket_medio)

# Função enviar e-mail:
def enviar_email(nome_da_loja, tabela):
    import smtplib
    import email.message

    server = smtplib.SMTP('smtp.gmail.com:587')  
    corpo_email = f""" 
    <p>Prezados,</p>
    <p>Segue o relatório de vendas</p>
    {tabela.to_html()}
    <p>Qualquer dúvida estou à disposição </p>
    """
    msg = email.message.Message()
    msg['Subject'] = f"Relatório de Vendas - {nome_da_loja}" 
    msg['From'] = 'remetente@gmail.com'
    msg['To'] = 'destinatario@gmail.com'
    password = "senha" 
    msg.add_header('Content-Type', 'text/html')
    msg.set_payload(corpo_email )
      
    s = smtplib.SMTP('smtp.gmail.com: 587')
    s.starttls()
    # Login Credentials for sending the mail
    s.login(msg['From'], password)
    s.sendmail(msg['From'], [msg['To']], msg.as_string().encode('utf-8'))
    print('Email enviado')

# Passo 5: Enviar o e-mail
tabela_completa = tabela_faturamento.join(tabela_quantidade).join(ticket_medio)
enviar_email("Diretoria", tabela_completa)

# Passo 6: Enviar e-mail para cada loja
lista_lojas = tabela_vendas["ID Loja"].unique()

for loja in lista_lojas:
  tabela_loja = tabela_vendas.loc[tabela_vendas["ID Loja"] == loja,["ID Loja", "Quantidade", "Valor Final"]]
  tabela_loja = tabela_loja.groupby("ID Loja").sum()
  tabela_loja["Ticket Medio"] = tabela_loja["Valor Final"] / tabela_loja["Quantidade"]
  enviar_email(loja, tabela_loja)
